Implement product mobile page
mlshv/fake-burberry-frontend pull request #1
Opened 2017-08-01 09:02 UTC by mlshv

Add Zeplin layout implementation for product mobile page

2017-08-01 12:18 UTC, evgenyrodionov commented
Проверю в 8

2017-08-01 18:18 UTC, evgenyrodionov commented
https://rawgit.com/mlshv/fake-burberry-frontend/feat/product-page/product.html

![image](https://user-images.githubusercontent.com/775692/28840150-c0a98426-76fe-11e7-8700-794e96b21a44.png)
![image](https://user-images.githubusercontent.com/775692/28840175-d13315fa-76fe-11e7-8315-9d9ec79e3ece.png)
![image](https://user-images.githubusercontent.com/775692/28840189-e408f032-76fe-11e7-93d7-dddb0daed6a4.png)
![image](https://user-images.githubusercontent.com/775692/28840213-f410270c-76fe-11e7-8812-6f3c624be451.png)
![image](https://user-images.githubusercontent.com/775692/28840227-fcca8982-76fe-11e7-87d1-5af73b91d602.png)

2017-08-01 18:19 UTC, imevro requested changes
фикси дизайн, кодстайл норм

2017-08-03 10:52 UTC, imevro requested changes
много дивов лишних, забиваешь на a11y, слабая консистетность — у тебя в цсс то пиксели, то ремы. да и нейминг адовый, возьми лучше БЭМ чем 10 слов через дефис писать

2017-08-03 10:52 UTC, evgenyrodionov commented on product.html
> +      <img class="logo" src="assets/logo.svg">
ссылкой должно быть

2017-08-03 10:52 UTC, evgenyrodionov commented on product.html
> +  </head>
какой бардак: мета, линк, линк, мета, линк, тайтл

2017-08-03 10:52 UTC, evgenyrodionov commented on product.html
> +          <button class="product-color-button product-color-button-brown"></button>
где тип, где значение внутри для скринридеров

2017-08-03 10:52 UTC, evgenyrodionov commented on product.html
> +                         product-props-button-size-select">Select a size</button>
это не product-props-button-size-select, это чёрная кнопка основная, которая будет переиспользоваться по сайту

2017-08-03 10:52 UTC, evgenyrodionov commented on product.html
> +          <img class="product-description-title-arrow" src="assets/triangle-up.svg">
в цсс

2017-08-03 10:52 UTC, evgenyrodionov commented on product.html
> +          <p>Specialist dry clean</p>
это тоже список

2017-08-03 10:52 UTC, evgenyrodionov commented on product.html
> +          <p>Coat length: 98cm/38.6in. This is based on a size UK 48 as proportions change slightly according to size.</p>
и это список

2017-08-03 10:52 UTC, evgenyrodionov commented on product.html
> +          <h2 class="product-shipping-title">Shipping &amp; returns</h2>
ты можешь использовать &, не ссы

2017-08-03 10:52 UTC, evgenyrodionov commented on product.html
> +          <div class="product-recomendations-card">
почему не ссылка

2017-08-03 10:52 UTC, evgenyrodionov commented on product.html
> +        <div class="product-recomendations-title">
зачем див?

2017-08-03 19:06 UTC, imevro requested changes

2017-08-03 19:06 UTC, evgenyrodionov commented on product.html
> +          <button class="product-color-button product-color-button-black" type="button" aria-label="black"></button>
почему бы не в тегах?

2017-08-04 08:28 UTC, imevro approved these changes

2017-08-04 19:51 UTC, evgenyrodionov commented
На след проверку

2017-08-05 09:44 UTC, evgenyrodionov commented
Шрифты

![image](https://user-images.githubusercontent.com/775692/28994642-d37494a8-79db-11e7-8611-1d4828784c2b.png)

2017-08-05 09:45 UTC, imevro requested changes

2017-08-05 09:45 UTC, evgenyrodionov commented on product.html
> +    <link rel="stylesheet" href="vendor/flexboxgrid2.css">
нахуя?

2017-08-05 11:03 UTC, mlshv commented
# Чеклист перед финальной домашкой
- Кодстайл - чек
- Фоллбэки шрифтов - чек
- Беспорядок в head - чек
- Большая вложенность - чек
- Семантика тегов - чек
- Семантика вёрстки - чек
- Кнопки - чек
- Описание - чек
- Иконки в разметке - чек
- Два файла для перевернутой стрелки - чек
- Суперфикс ширины или высоты картинок - чек
- Смешивание классов сетки и своих - чек
- Переопределение классов сетки - чек
- Стили на тегах или айди - чек
- a11y — accessibility - чек
- Согласованность - пиксели чек, дивы/секшены выясняю
- Сброс дефолтных стилей - чек
- outline: none - чек
- Отсутствие сетки - чек, естественно
- Нейминг по порядку - чек :)
- Задротские селекторы - чек, нет их
- Плохая работа с заголовками - чек, проверил через расширение
- Списки не для списков - чек
- Ширина и высота в ХТМЛ - чек

Исправления по ревью - чек

Я готов

2017-08-06 07:54 UTC, imevro approved these changes

2017-08-06 07:55 UTC, merged

2017-08-06 07:55 UTC, evgenyrodionov commented
Переключаешься на мастер, гит пулл ориджин мастер --ребейз, новые бранчи от этого нового мастера