Add state to interactable components
mlshv/fake-burberry-frontend pull request #10
Opened 2017-08-26 13:21 UTC by mlshv

Что реализовано:
- Лайки
- Дропдауны фильтров
- Выбор страны в шапке

2017-08-28 17:04 UTC, mlshv commented
Добавил выезжающее меню

2017-08-28 17:21 UTC, evgenyrodionov commented
Уехала стрелка плюс клик по ней не работает
![image](https://user-images.githubusercontent.com/775692/29784914-6b6cfb7e-8c2e-11e7-92a8-6fb9503462c5.png)

2017-08-28 17:22 UTC, evgenyrodionov commented
`cursor: pointer` не забывай при ховере на кликабельные элементы — в хедере такого нет, в фильтрах тоже

2017-08-28 17:22 UTC, evgenyrodionov commented
Дыра какая-то, откуда там фикс ширина?

![image](https://user-images.githubusercontent.com/775692/29784995-a080cec6-8c2e-11e7-885c-efa56617254b.png)

2017-08-28 17:23 UTC, evgenyrodionov commented
?
![image](https://user-images.githubusercontent.com/775692/29785009-ae1dbe40-8c2e-11e7-846c-396ef1fd5382.png)

2017-08-28 17:23 UTC, evgenyrodionov commented
Меню не доделано — нет переходов внутренних, посмотри макеты

2017-08-28 17:41 UTC, imevro requested changes

2017-08-28 17:41 UTC, evgenyrodionov commented on src/App.jsx
> +    sideNavActive: true,
opened скорее

2017-08-28 17:41 UTC, evgenyrodionov commented on src/App.jsx
> +  toggleSideNav() {
можно использовать arrow-функцию чтобы не биндить скоуп

2017-08-28 17:41 UTC, evgenyrodionov commented on src/App.jsx
> +    this.setState(state => ({
state → prevState, так логичнее

2017-08-28 17:41 UTC, evgenyrodionov commented on src/Header/LocationSelector.jsx
> +        currency: '£',
я могу шопиться в юкей и смотреть в рублях

2017-08-28 17:41 UTC, evgenyrodionov commented on src/Header/LocationSelector.jsx
> +          {this.state.locations.map(l =>
не скрщй плз слкшм тжл чтть

2017-08-28 17:41 UTC, evgenyrodionov commented on src/Products/Card/LikeButton.jsx
> +        <svg
вынеси свг в отдельный компонент

2017-08-28 17:41 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +    width: 23.5625rem;
чтооо это

2017-08-28 17:41 UTC, evgenyrodionov commented on src/Products/List/Filters.jsx
> +    dimInactiveFilters: false,
? не понял

2017-08-28 17:41 UTC, evgenyrodionov commented on src/SideNavigation/ButtonSelect.jsx
> +          {this.state.selectedValue || this.props.options[0]}
лучше храни дефолтное велью чем вот этот или

2017-08-28 17:41 UTC, evgenyrodionov commented on src/SideNavigation/ButtonSelect.jsx
> +          {this.state.selectedValue || this.props.options[0]}
типа это бизнес-логика же

2017-08-28 17:41 UTC, evgenyrodionov commented on src/SideNavigation/ButtonSelect.jsx
> +            this.setState({ value: select.value });
почему это тут инлайном? вынеси в метод

2017-08-29 08:24 UTC, mlshv commented on src/Header/LocationSelector.jsx
> +        currency: '£',
Burberry так не считает
![image](https://user-images.githubusercontent.com/16861579/29811554-a21bb47a-8cac-11e7-971e-23c120d31eb9.png)

2017-08-29 08:26 UTC, mlshv commented on src/Header/LocationSelector.jsx
> +          {this.state.locations.map(l =>
> "Single-letter names should ONLY be used as local variables inside short methods" - Robert Martin

So why not?

2017-08-29 16:35 UTC, mlshv commented
- Всё исправил (кроме подкатегорий в мобильной навигации, это сделаю завтра)
- Добавил выбор размера и цвета

2017-08-29 19:31 UTC, evgenyrodionov commented
А чё такое длинное?

![image](https://user-images.githubusercontent.com/775692/29840211-d4c30394-8d09-11e7-8044-818cc02f809c.png)

2017-08-29 19:38 UTC, imevro requested changes

2017-08-29 19:38 UTC, evgenyrodionov commented on src/App.jsx
> +    const toggleSideNav = () => {
воу воу воу, почему это в рендере? в рендере нельзя обновлять стейт!

2017-08-29 19:38 UTC, evgenyrodionov commented on src/Header/index.jsx
> +            locations={['United Kingdom (£)', 'United States ($)', 'Russian Federation (₽)']}
лучше массивом храни

2017-08-29 19:38 UTC, evgenyrodionov commented on src/Products/Card/LikeButton.jsx
> +        <HeartIcon {...(this.state.active ? { fillColor: '#171717' } : '')} />
почему fillColor если там атрибут называется fill? смысл этого усложнения?

2017-08-29 19:38 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +  dimmed: PropTypes.bool,
что этот проп вообще значит?

2017-08-29 19:38 UTC, evgenyrodionov commented on src/Products/List/Filters.jsx
> +              dimmed={this.state.activeFilter !== undefined && this.state.activeFilter !== 3}
3? какой-то меджик намбер. управляйся лучше с уникальными ключами

2017-08-29 19:38 UTC, evgenyrodionov commented on src/Products/Show/index.jsx
> +  const sampleSizes = ['S', 'M', 'L', 'XL'];
нет нужды это держать в рендере — рендер вызывается каждый раз при обновлении пропов и поэтому это всё будет создаваться тоже каждый раз

2017-08-30 09:38 UTC, mlshv commented
Всё поправил
https://mlshv-burberry-fake-shop-for-study-dev.now.sh/

2017-08-30 18:45 UTC, evgenyrodionov commented
А почему футер не работает?

2017-08-30 18:47 UTC, evgenyrodionov commented
Какое значение выбрано?

![image](https://user-images.githubusercontent.com/775692/29889421-c5f1c760-8dcc-11e7-8750-fe0228d4a3de.png)

2017-08-30 18:52 UTC, imevro requested changes

2017-08-30 18:52 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
>      if (on === false && on === this.state.active) return;
я же говорил про нулевые ретёрны

2017-08-30 18:52 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
>        () => ({ active: !this.state.active }),
если ты тут используешь функциональный сетстейт, то почему обращаешься к this.state?

https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1

2017-08-30 18:52 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +          <Button active={this.state.active} inactive={this.props.inactive} onClick={this.toggle}>
булеаны префиксуются через `is*`

2017-08-31 08:58 UTC, mlshv commented
Всё пофиксил, селекты в футере сделал
https://mlshv-burberry-fake-shop-for-study-dev.now.sh/

2017-08-31 12:51 UTC, evgenyrodionov commented
а где смена контента в меню?

2017-08-31 12:53 UTC, imevro requested changes

2017-08-31 12:53 UTC, evgenyrodionov commented on src/Products/List/Filters.jsx
> +                  isInactive={
лол может лучше передавать `isActive`?

2017-08-31 17:03 UTC, mlshv commented
Пофиксил нейминг и начал делать боковое подменю: вёрстка уже готова

2017-08-31 18:20 UTC, imevro requested changes
жду меню

2017-08-31 20:17 UTC, mlshv commented
Ну чё, готово
https://mlshv-burberry-fake-shop-for-study-dev.now.sh

2017-09-01 10:54 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29966984-06459ca0-8f1d-11e7-8ace-3ca8053b0023.png)

2017-09-01 11:02 UTC, evgenyrodionov commented on src/SideNavigation/index.jsx
> +    image:
а зачем ширина тут хранится

2017-09-01 14:40 UTC, mlshv commented
TL;DR пофиксил всё и даже больше
https://mlshv-burberry-fake-shop-for-study-dev.now.sh

- Убрал боковое меню на md+ экранах
- Убрал горизонтальный скролл в боковом меню (он там был, но ты не заметил)
- Убрал вертикальный скролл в подменю (высота подменю была >= высоте корневого меню)
- Убрал ширину картинки-обложки подменю в ссылке
- Теперь fragrance-related ссылки в Beauty указывают на соответствующие разделы в /men и /women

2017-09-01 17:20 UTC, imevro approved these changes

2017-09-01 17:21 UTC, evgenyrodionov commented
Раунд

2017-09-01 17:21 UTC, evgenyrodionov commented
Жди апи)

2017-09-01 17:21 UTC, merged