Split product page into components using React and Styled Components
mlshv/fake-burberry-frontend pull request #3
Opened 2017-08-09 15:13 UTC by mlshv

2017-08-09 18:14 UTC, imevro requested changes

2017-08-09 18:14 UTC, evgenyrodionov commented on src/Header/Header.js
> +function Header() {
если сделаешь сразу экспорт дефолт, то не нужно будет придумать `HeaderComponent`

2017-08-09 18:14 UTC, evgenyrodionov commented on src/Product/ColorButton.js
> +      color={props.colorHex}
colorHex? wtf?

2017-08-09 18:14 UTC, evgenyrodionov commented on src/Product/Product.js
> +          <Properties />
Properties?

2017-08-09 18:14 UTC, evgenyrodionov commented on src/common/Accordion.js
> +    this.setState({ active: !this.state.active })
https://medium.freecodecamp.org/functional-setstate-is-the-future-of-react-374f30401b6b

2017-08-09 18:14 UTC, evgenyrodionov commented on src/common/Accordion.js
> +      active: props.active
либо пропы либо стейт, иначе у тебя рассинхронизация по данным: с пропов приходит false, со стейта true. Либо придётся ебаться и на изменение пропов подписываться и обновлять стейт. Оно тебе надо?

2017-08-09 18:14 UTC, evgenyrodionov commented on src/common/Accordion.js
> +  toggleActive() {
Просто toggle это ок

2017-08-09 18:14 UTC, evgenyrodionov commented on src/common/Accordion.js
> +          <Title hideMd={this.props.hideTitleMd}>
hideMd={this.props.hideTitleMd}? согласованность ок вообще

2017-08-09 18:14 UTC, evgenyrodionov commented on src/common/Accordion.js
> +        noTopBorder={this.props.noTopBorder}
не понял что это

2017-08-09 18:14 UTC, evgenyrodionov commented on src/App.js
> +import Product from './Product/Product'
читай телеграф про индекс

2017-08-10 06:12 UTC, mlshv commented on src/Product/Product.js
> +          <Properties />
property – an attribute, quality, or characteristic of something.
Ну типо свойства товара. Не катит?

2017-08-10 06:27 UTC, mlshv commented on src/common/Accordion.js
> +    this.setState({ active: !this.state.active })
спасибо за статью, не знал

но действительно ли нужно делать это функционально для переключения одного флага?

2017-08-10 10:17 UTC, imevro requested changes

2017-08-10 10:17 UTC, evgenyrodionov commented on src/Product/ColorButton.js
> +    <ColorButton color={props.colorValue} active={props.active} type="button">
color={colorValue}

2017-08-10 10:17 UTC, evgenyrodionov commented on src/Product/MainPanel.js
> +        <ColorButton colorName="black" colorValue="#232122" />
можно просто name и value — зачем префиксовать `color`, если компонент называется ColorButton

2017-08-10 10:17 UTC, evgenyrodionov commented on src/Product/ShippingAccordion.js
> +class ShippingAccordion extends Accordion {
зачем тут класс?

2017-08-10 17:33 UTC, imevro requested changes

2017-08-10 17:33 UTC, evgenyrodionov commented on src/Product/Recommendations.js
> +            price="27 000 руб."
числом передавай, не строкой

2017-08-10 17:33 UTC, evgenyrodionov commented on src/Product/ShippingAccordion.js
> +class ShippingAccordion extends Accordion {
и всё же, зачем тут класс?

2017-08-10 17:33 UTC, evgenyrodionov commented on src/Product/ShippingAccordion.js
> +class ShippingAccordion extends Accordion {
всё, увидел. Не надо наследоваться от аккордеона, ООП — неявное говно, переделывай

2017-08-10 17:33 UTC, evgenyrodionov commented on src/Product/Showcase.js
> +    height: 576px;
откуда суперфикс

2017-08-10 17:33 UTC, evgenyrodionov commented on src/Product/Showcase.js
> +      <ShowcaseImage
зачем все эти префиксы Showcase если ты в файле Showcase?

2017-08-10 17:33 UTC, evgenyrodionov commented on src/Product/ShippingAccordion.js
> +class ShippingAccordion extends Accordion {
я не вижу ни одной причины не переиспользовать компонент Accordion, смысл его наследовать? чем эти два файла друг от друга отличаются?

2017-08-11 11:25 UTC, imevro requested changes

2017-08-11 11:25 UTC, evgenyrodionov commented on src/Product/RecommendationCard.js
> +import formatPrice from '../common/formatPrice'
ой давай без своих велосипедов, похвально, конечно, но есть react-intl

2017-08-11 11:25 UTC, evgenyrodionov commented on src/common/formatPrice.js
> +const formats = {
но не могу не отметить что красавчик, круто сделал. разве что почему numberWithSpaces ниже чем её вызов

2017-08-11 11:25 UTC, evgenyrodionov commented on src/common/formatPrice.js
> +function numberWithSpaces(x) {
x тупое имя аргумента

2017-08-11 11:27 UTC, mlshv commented on src/Product/RecommendationCard.js
> +import formatPrice from '../common/formatPrice'
открываю вчера, читаю фичи, про цену ни слова, вот я и забил :)

2017-08-11 12:23 UTC, mlshv commented
Слетело время. Коммит [dd32823](https://github.com/mlshv/fake-burberry-frontend/pull/3/commits/dd32823f905440e9e186e5fae5c9d9f69d30b51d) засчитался раньше

2017-08-11 17:18 UTC, imevro requested changes

2017-08-11 17:18 UTC, evgenyrodionov commented on src/index.js
> +ReactDOM.render(
в этом файле у нас к реакту относится только `render(<App />)`, поэтому засорять провайдерами не нужно

2017-08-12 12:10 UTC, imevro approved these changes
вроде норм, делай десктоп в отдельном бранче

2017-08-13 20:50 UTC, merged