Add products list
mlshv/fake-burberry-frontend pull request #8
Opened 2017-08-17 22:23 UTC by mlshv

2017-08-18 16:41 UTC, mlshv commented
Products list: https://build-gbsnffwfaa.now.sh/
Product page: https://build-gbsnffwfaa.now.sh/men/trench-coats/long-cotton-gabardine-car-coat

2017-08-18 17:47 UTC, evgenyrodionov commented
Ссылок на карточках нет

2017-08-18 17:49 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29470820-841c96a0-8456-11e7-91be-fc4dae9e8bc2.png)
![image](https://user-images.githubusercontent.com/775692/29470830-8c4434b4-8456-11e7-8b4a-ac4595f78f6e.png)
![image](https://user-images.githubusercontent.com/775692/29470848-a3accbc0-8456-11e7-8f29-72cd12e724a9.png)
![image](https://user-images.githubusercontent.com/775692/29470856-ab349238-8456-11e7-8777-7ac86a7783e7.png)

2017-08-18 17:49 UTC, evgenyrodionov commented
Перепроверь макет

2017-08-18 22:55 UTC, mlshv commented
Отличия с макетом: разные отступы между кнопками и рандомно прилепленая кнопка "More"
![Top section](https://user-images.githubusercontent.com/16861579/29480071-83972eac-847e-11e7-89c1-d3f7cf566b34.png)

У трёх правых верхних карточек сердечки немого по-другому приделаны, названия отличаются от официальных (с сайта Burberry)
![Product list](https://user-images.githubusercontent.com/16861579/29480118-d75bce8a-847e-11e7-83b8-0e4658842a19.png)

Опять что-то не так с картинками
![image](https://user-images.githubusercontent.com/16861579/29480204-45545f38-847f-11e7-8005-3a0f3afed320.png)

На больших экранах сетка немного не в форме
![image](https://user-images.githubusercontent.com/16861579/29480303-0a643d98-8480-11e7-871a-83b07d7d8ee0.png)

Из-за этого взаимное расположение карточек и сердечек внутри них тоже отличается
![image](https://user-images.githubusercontent.com/16861579/29480334-4c3504c8-8480-11e7-8b81-7dc0d0c2cfab.png)

Всё остальное ок. Вот билд:
https://build-gxkozykssg.now.sh/

2017-08-19 09:24 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29485352-37f1c6f0-84d9-11e7-9080-798e086bd67c.png)
![image](https://user-images.githubusercontent.com/775692/29485356-42cf1b7c-84d9-11e7-96bf-76cb10b69bc7.png)
![image](https://user-images.githubusercontent.com/775692/29485360-5915ad7e-84d9-11e7-9aa5-ebca026cd300.png)

2017-08-19 09:25 UTC, evgenyrodionov commented
Планшет
Во-первых, там всего 4 карточки вместо 8 — почему?

![image](https://user-images.githubusercontent.com/775692/29485370-72432c40-84d9-11e7-8520-cda01ec120b4.png)
![image](https://user-images.githubusercontent.com/775692/29485374-7b8130cc-84d9-11e7-85a1-25dc292cbb09.png)
![image](https://user-images.githubusercontent.com/775692/29485376-8bf084f8-84d9-11e7-820a-cfab784c9f48.png)

2017-08-19 09:27 UTC, evgenyrodionov commented
Мобайл

![image](https://user-images.githubusercontent.com/775692/29485382-a2b07644-84d9-11e7-8176-dedb5e2ceb5e.png)

Поправь дыру плз
![image](https://user-images.githubusercontent.com/775692/29485386-b1620acc-84d9-11e7-9f6d-7ead6753d812.png)

2017-08-19 10:18 UTC, mlshv commented
Фиксанул https://build-fjnrrsugeu.now.sh

2017-08-19 15:14 UTC, mlshv commented
https://build-gakqqhsdyh.now.sh

2017-08-19 19:39 UTC, evgenyrodionov commented
Поправь шрифты
![image](https://user-images.githubusercontent.com/775692/29489682-4539677c-852f-11e7-813a-97a5b8903011.png)

2017-08-19 19:45 UTC, imevro requested changes

2017-08-19 19:45 UTC, evgenyrodionov commented on src/App.jsx
> +import ProductsList from './Products/List';
Почему бы не просто Products?

2017-08-19 19:45 UTC, evgenyrodionov commented on src/Products/Card.jsx
> +    <Link to={props.link}>
to={link}?

2017-08-19 19:45 UTC, evgenyrodionov commented on src/Products/List/Jumbotron.jsx
> +    let text = { __html: this.props.text };
без мутабельности

2017-08-19 19:45 UTC, evgenyrodionov commented on src/Products/List/Jumbotron.jsx
> +    this.maxShowedTextLength = 194;
а зачем это хранить в классе если это обычная статичная константа?

2017-08-19 19:45 UTC, evgenyrodionov commented on src/Products/Show/Recommendations.jsx
> +          image="/img/recommend4.jpg"
читай телеграф про паблик урл раз
используй урлы с сайта берберри два

2017-08-19 22:29 UTC, mlshv commented
Всё пофиксил: https://build-vsqtptnxwp.now.sh/

2017-08-20 09:25 UTC, imevro approved these changes

2017-08-20 09:25 UTC, merged